// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: grpc/auction.proto

package auction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidOutcome int32

const (
	BidOutcome_BID_OUTCOME_UNSPECIFIED BidOutcome = 0
	BidOutcome_SUCCESS                 BidOutcome = 1
	BidOutcome_FAIL                    BidOutcome = 2
	BidOutcome_EXCEPTION               BidOutcome = 3
)

// Enum value maps for BidOutcome.
var (
	BidOutcome_name = map[int32]string{
		0: "BID_OUTCOME_UNSPECIFIED",
		1: "SUCCESS",
		2: "FAIL",
		3: "EXCEPTION",
	}
	BidOutcome_value = map[string]int32{
		"BID_OUTCOME_UNSPECIFIED": 0,
		"SUCCESS":                 1,
		"FAIL":                    2,
		"EXCEPTION":               3,
	}
)

func (x BidOutcome) Enum() *BidOutcome {
	p := new(BidOutcome)
	*p = x
	return p
}

func (x BidOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BidOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_auction_proto_enumTypes[0].Descriptor()
}

func (BidOutcome) Type() protoreflect.EnumType {
	return &file_grpc_auction_proto_enumTypes[0]
}

func (x BidOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BidOutcome.Descriptor instead.
func (BidOutcome) EnumDescriptor() ([]byte, []int) {
	return file_grpc_auction_proto_rawDescGZIP(), []int{0}
}

type BidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     string                 `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	BidderId      string                 `protobuf:"bytes,2,opt,name=bidder_id,json=bidderId,proto3" json:"bidder_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	mi := &file_grpc_auction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_grpc_auction_proto_rawDescGZIP(), []int{0}
}

func (x *BidRequest) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

func (x *BidRequest) GetBidderId() string {
	if x != nil {
		return x.BidderId
	}
	return ""
}

func (x *BidRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type BidResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Outcome         BidOutcome             `protobuf:"varint,1,opt,name=outcome,proto3,enum=Auction.BidOutcome" json:"outcome,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	HighestBid      int64                  `protobuf:"varint,3,opt,name=highest_bid,json=highestBid,proto3" json:"highest_bid,omitempty"`
	HighestBidderId string                 `protobuf:"bytes,4,opt,name=highest_bidder_id,json=highestBidderId,proto3" json:"highest_bidder_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BidResponse) Reset() {
	*x = BidResponse{}
	mi := &file_grpc_auction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse) ProtoMessage() {}

func (x *BidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse.ProtoReflect.Descriptor instead.
func (*BidResponse) Descriptor() ([]byte, []int) {
	return file_grpc_auction_proto_rawDescGZIP(), []int{1}
}

func (x *BidResponse) GetOutcome() BidOutcome {
	if x != nil {
		return x.Outcome
	}
	return BidOutcome_BID_OUTCOME_UNSPECIFIED
}

func (x *BidResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BidResponse) GetHighestBid() int64 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *BidResponse) GetHighestBidderId() string {
	if x != nil {
		return x.HighestBidderId
	}
	return ""
}

type ResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     string                 `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultRequest) Reset() {
	*x = ResultRequest{}
	mi := &file_grpc_auction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRequest) ProtoMessage() {}

func (x *ResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRequest.ProtoReflect.Descriptor instead.
func (*ResultRequest) Descriptor() ([]byte, []int) {
	return file_grpc_auction_proto_rawDescGZIP(), []int{2}
}

func (x *ResultRequest) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

type ResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsClosed      bool                   `protobuf:"varint,1,opt,name=is_closed,json=isClosed,proto3" json:"is_closed,omitempty"`
	HighestBid    int64                  `protobuf:"varint,2,opt,name=highest_bid,json=highestBid,proto3" json:"highest_bid,omitempty"`
	WinnerId      string                 `protobuf:"bytes,3,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultResponse) Reset() {
	*x = ResultResponse{}
	mi := &file_grpc_auction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultResponse) ProtoMessage() {}

func (x *ResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultResponse.ProtoReflect.Descriptor instead.
func (*ResultResponse) Descriptor() ([]byte, []int) {
	return file_grpc_auction_proto_rawDescGZIP(), []int{3}
}

func (x *ResultResponse) GetIsClosed() bool {
	if x != nil {
		return x.IsClosed
	}
	return false
}

func (x *ResultResponse) GetHighestBid() int64 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *ResultResponse) GetWinnerId() string {
	if x != nil {
		return x.WinnerId
	}
	return ""
}

func (x *ResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_grpc_auction_proto protoreflect.FileDescriptor

const file_grpc_auction_proto_rawDesc = "" +
	"\n" +
	"\x12grpc/auction.proto\x12\aAuction\"`\n" +
	"\n" +
	"BidRequest\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\tR\tauctionId\x12\x1b\n" +
	"\tbidder_id\x18\x02 \x01(\tR\bbidderId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"\xa3\x01\n" +
	"\vBidResponse\x12-\n" +
	"\aoutcome\x18\x01 \x01(\x0e2\x13.Auction.BidOutcomeR\aoutcome\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vhighest_bid\x18\x03 \x01(\x03R\n" +
	"highestBid\x12*\n" +
	"\x11highest_bidder_id\x18\x04 \x01(\tR\x0fhighestBidderId\".\n" +
	"\rResultRequest\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\tR\tauctionId\"\x85\x01\n" +
	"\x0eResultResponse\x12\x1b\n" +
	"\tis_closed\x18\x01 \x01(\bR\bisClosed\x12\x1f\n" +
	"\vhighest_bid\x18\x02 \x01(\x03R\n" +
	"highestBid\x12\x1b\n" +
	"\twinner_id\x18\x03 \x01(\tR\bwinnerId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage*O\n" +
	"\n" +
	"BidOutcome\x12\x1b\n" +
	"\x17BID_OUTCOME_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\b\n" +
	"\x04FAIL\x10\x02\x12\r\n" +
	"\tEXCEPTION\x10\x032v\n" +
	"\aAuction\x120\n" +
	"\x03Bid\x12\x13.Auction.BidRequest\x1a\x14.Auction.BidResponse\x129\n" +
	"\x06Result\x12\x16.Auction.ResultRequest\x1a\x17.Auction.ResultResponseB1Z/github.com/andersgrangaard/Auction/grpc;auctionb\x06proto3"

var (
	file_grpc_auction_proto_rawDescOnce sync.Once
	file_grpc_auction_proto_rawDescData []byte
)

func file_grpc_auction_proto_rawDescGZIP() []byte {
	file_grpc_auction_proto_rawDescOnce.Do(func() {
		file_grpc_auction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_auction_proto_rawDesc), len(file_grpc_auction_proto_rawDesc)))
	})
	return file_grpc_auction_proto_rawDescData
}

var file_grpc_auction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_auction_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_auction_proto_goTypes = []any{
	(BidOutcome)(0),        // 0: Auction.BidOutcome
	(*BidRequest)(nil),     // 1: Auction.BidRequest
	(*BidResponse)(nil),    // 2: Auction.BidResponse
	(*ResultRequest)(nil),  // 3: Auction.ResultRequest
	(*ResultResponse)(nil), // 4: Auction.ResultResponse
}
var file_grpc_auction_proto_depIdxs = []int32{
	0, // 0: Auction.BidResponse.outcome:type_name -> Auction.BidOutcome
	1, // 1: Auction.Auction.Bid:input_type -> Auction.BidRequest
	3, // 2: Auction.Auction.Result:input_type -> Auction.ResultRequest
	2, // 3: Auction.Auction.Bid:output_type -> Auction.BidResponse
	4, // 4: Auction.Auction.Result:output_type -> Auction.ResultResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_auction_proto_init() }
func file_grpc_auction_proto_init() {
	if File_grpc_auction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_auction_proto_rawDesc), len(file_grpc_auction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_auction_proto_goTypes,
		DependencyIndexes: file_grpc_auction_proto_depIdxs,
		EnumInfos:         file_grpc_auction_proto_enumTypes,
		MessageInfos:      file_grpc_auction_proto_msgTypes,
	}.Build()
	File_grpc_auction_proto = out.File
	file_grpc_auction_proto_goTypes = nil
	file_grpc_auction_proto_depIdxs = nil
}
