// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: grpc/replication.proto

package auction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppendBidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     string                 `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	BidderId      string                 `protobuf:"bytes,2,opt,name=bidder_id,json=bidderId,proto3" json:"bidder_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendBidRequest) Reset() {
	*x = AppendBidRequest{}
	mi := &file_grpc_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendBidRequest) ProtoMessage() {}

func (x *AppendBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendBidRequest.ProtoReflect.Descriptor instead.
func (*AppendBidRequest) Descriptor() ([]byte, []int) {
	return file_grpc_replication_proto_rawDescGZIP(), []int{0}
}

func (x *AppendBidRequest) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

func (x *AppendBidRequest) GetBidderId() string {
	if x != nil {
		return x.BidderId
	}
	return ""
}

func (x *AppendBidRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AppendBidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendBidResponse) Reset() {
	*x = AppendBidResponse{}
	mi := &file_grpc_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendBidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendBidResponse) ProtoMessage() {}

func (x *AppendBidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendBidResponse.ProtoReflect.Descriptor instead.
func (*AppendBidResponse) Descriptor() ([]byte, []int) {
	return file_grpc_replication_proto_rawDescGZIP(), []int{1}
}

func (x *AppendBidResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AppendBidResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_grpc_replication_proto protoreflect.FileDescriptor

const file_grpc_replication_proto_rawDesc = "" +
	"\n" +
	"\x16grpc/replication.proto\x12\aAuction\"f\n" +
	"\x10AppendBidRequest\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\tR\tauctionId\x12\x1b\n" +
	"\tbidder_id\x18\x02 \x01(\tR\bbidderId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"G\n" +
	"\x11AppendBidResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2Q\n" +
	"\vReplication\x12B\n" +
	"\tAppendBid\x12\x19.Auction.AppendBidRequest\x1a\x1a.Auction.AppendBidResponseB1Z/github.com/andersgrangaard/Auction/grpc;auctionb\x06proto3"

var (
	file_grpc_replication_proto_rawDescOnce sync.Once
	file_grpc_replication_proto_rawDescData []byte
)

func file_grpc_replication_proto_rawDescGZIP() []byte {
	file_grpc_replication_proto_rawDescOnce.Do(func() {
		file_grpc_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_replication_proto_rawDesc), len(file_grpc_replication_proto_rawDesc)))
	})
	return file_grpc_replication_proto_rawDescData
}

var file_grpc_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_replication_proto_goTypes = []any{
	(*AppendBidRequest)(nil),  // 0: Auction.AppendBidRequest
	(*AppendBidResponse)(nil), // 1: Auction.AppendBidResponse
}
var file_grpc_replication_proto_depIdxs = []int32{
	0, // 0: Auction.Replication.AppendBid:input_type -> Auction.AppendBidRequest
	1, // 1: Auction.Replication.AppendBid:output_type -> Auction.AppendBidResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_replication_proto_init() }
func file_grpc_replication_proto_init() {
	if File_grpc_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_replication_proto_rawDesc), len(file_grpc_replication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_replication_proto_goTypes,
		DependencyIndexes: file_grpc_replication_proto_depIdxs,
		MessageInfos:      file_grpc_replication_proto_msgTypes,
	}.Build()
	File_grpc_replication_proto = out.File
	file_grpc_replication_proto_goTypes = nil
	file_grpc_replication_proto_depIdxs = nil
}
